
services:
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5001:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/blogeducacionaloz
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: