name: CI/CD Blog Educacional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build --prefix frontend

      - name: Build backend
        run: npm run build --prefix backend

      - name: Skip tests
        run: echo "Skipping tests for now"

      - name: Deploy to Docker
        run: |
          docker-compose -f docker-compose.yml up -d --build